# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://jamk-it.github.io/TTMS0400-web-visualisointi/
title: TTMS0400 Web-visualisointi
email: paavo.nelimarkka@jamk.fi

author: JAMK-IT
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016. &nbsp; Project maintained by JAMK-IT. &nbsp; Hosted on GitHub Pages.'
credits: 'Credits: Open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: code
    url: https://github.com/JAMK-IT/TTMS0400-web-visualisointi
    icon: fa fa-github fa-fw
  - title: asio
    url: https://asio.jamk.fi/pls/asio/asio_ectskuv1.kurssin_ks?ktun=TTMS0400&knro=&noclose=%20&lan=fi

